import NavBar from "@/component/NavBar";
import "./globals.scss";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Home from "./page";

const poppins = Poppins({
  weight: "500",
  subsets: ["devanagari", "latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Home/>
        {children}
      </body>
    </html>
  );
}
